# Generated by Django 5.2.15 on 2026-06-07 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "log_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("action", models.CharField(max_length=255)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
