# Generated by Django 5.2.15 on 2026-06-07 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterCategory",
            fields=[
                (
                    "category_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("category_name", models.CharField(db_column="name", max_length=100)),
                ("icon", models.CharField(default="fa-tag", max_length=50)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Master Categories",
                "db_table": "master_categories",
            },
        ),
        migrations.CreateModel(
            name="UserCategory",
            fields=[
                (
                    "user_category_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("is_custom", models.BooleanField(default=True)),
                (
                    "budget_limit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_associated",
                        to="categories.mastercategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Categories",
                "db_table": "user_categories",
                "unique_together": {("user", "category")},
            },
        ),
    ]
