# Generated by Django 5.2.15 on 2026-06-07 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBudget",
            fields=[
                (
                    "budget_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        db_column="limit_amount", decimal_places=2, max_digits=12
                    ),
                ),
                ("year", models.IntegerField(db_column="budget_year")),
                ("month", models.IntegerField(db_column="budget_month")),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_budgets",
                        to="categories.mastercategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "category_budgets",
                "unique_together": {("user", "category", "year", "month")},
            },
        ),
    ]
